export default interface MemberObj {
    UniqueID: Number,
    Time: String,
    EmailAddress: String,
    ID: String,
    NameLastname: String,
    Nickname: String,
    EmailKU: String,
    Social: String,
    LineID: String,
    Tel: String,
    Address: String,
    Picture: String,
    Transcript: String,
    MBTI: String,
    Club: String,
    Talent: String,
    Tools: String,
    Hobbies: String,
    Experience: String,
    Expect: String,
    Interest: String,
}